language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init 
  - git config user.name "liyy7520"
  - git config user.email "po13001000260@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/liyy7520/liyy752019.github.io
